In [3]:
import warnings 
warnings.filterwarnings(action='ignore')

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df = pd.read_csv("framingham.csv")
df

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1,39,4.0,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,0,46,2.0,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,1,48,1.0,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,0,61,3.0,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,0,46,3.0,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4235,0,48,2.0,1,20.0,NaN,0,0,0,248.0,131.0,72.0,22.00,84.0,86.0,0
4236,0,44,1.0,1,15.0,0.0,0,0,0,210.0,126.5,87.0,19.16,86.0,NaN,0
4237,0,52,2.0,0,0.0,0.0,0,0,0,269.0,133.5,83.0,21.47,80.0,107.0,0
4238,1,40,3.0,0,0.0,0.0,0,1,0,185.0,141.0,98.0,25.60,67.0,72.0,0
4239,0,39,3.0,1,30.0,0.0,0,0,0,196.0,133.0,86.0,20.91,85.0,80.0,0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4240 entries, 0 to 4239
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   male             4240 non-null   int64
 1   age              4240 non-null   int64
 2   education        4135 non-null   float64
 3   currentSmoker    4240 non-null   int64
 4   cigsPerDay       4211 non-null   float64
 5   BPMeds           4187 non-null   float64
 6   prevalentStroke  4240 non-null   int64
 7   prevalentHyp     4240 non-null   int64
 8   diabetes         4240 non-null   int64
 9   totChol          4190 non-null   float64
 10  sysBP            4240 non-null   float64
 11  diaBP            4240 non-null   float64
 12  BMI              4221 non-null   float64
 13  heartRate        4239 non-null   float64
 14  glucose          3852 non-null   float64
 15  TenYearCHD       4240 non-null   int64
dtypes: float64(9), int64(7)
memory usage: 530.1 KB

In [7]:
df.describe()

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
count,4240.000000,4240.000000,4135.000000,4240.000000,4211.000000,4187.000000,4240.000000,4240.000000,4240.000000,4190.000000,4240.000000,4240.000000,4221.000000,4239.000000,3852.000000,4240.000000
mean,0.429245,49.580189,1.979444,0.494104,9.005937,0.029615,0.005896,0.310613,0.025708,236.699523,132.354599,82.897759,25.800801,75.878981,81.963655,0.151887
std,0.495027,8.572942,1.019791,0.500024,11.922462,0.169544,0.076569,0.462799,0.158280,44.591284,22.033300,11.910394,4.079840,12.025348,23.954335,0.358953
min,0.000000,32.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,107.000000,83.500000,48.000000,15.540000,44.000000,40.000000,0.000000
25%,0.000000,42.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,206.000000,117.000000,75.000000,23.070000,68.000000,71.000000,0.000000
50%,0.000000,49.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,234.000000,128.000000,82.000000,25.400000,75.000000,78.000000,0.000000
75%,1.000000,56.000000,3.000000,1.000000,20.000000,0.000000,0.000000,1.000000,0.000000,263.000000,144.000000,90.000000,28.040000,83.000000,87.000000,0.000000
max,1.000000,70.000000,4.000000,1.000000,70.000000,1.000000,1.000000,1.000000,1.000000,696.000000,295.000000,142.500000,56.800000,143.000000,394.000000,1.000000

In [8]:
df.isnull().sum()

male                 0
age                  0
education          105
currentSmoker        0
cigsPerDay          29
BPMeds              53
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol             50
sysBP                0
diaBP                0
BMI                 19
heartRate            1
glucose            388
TenYearCHD           0
dtype: int64

In [9]:
df['education'] = df['education'].fillna(df['education'].mean())
df['cigsPerDay'] = df['cigsPerDay'].fillna(df['cigsPerDay'].mean())
df['BPMeds'] = df['BPMeds'].fillna(df['BPMeds'].mean())
df['BMI'] = df['BMI'].fillna(df['BMI'].mean())
df['heartRate'] = df['heartRate'].fillna(df['heartRate'].mean())
df['glucose'] =df['glucose'].fillna(df['glucose'].mean())
df['totChol'] =df['totChol'].fillna(df['totChol'].mean())

In [10]:
df.isnull().sum()

male               0
age                0
education          0
currentSmoker      0
cigsPerDay         0
BPMeds             0
prevalentStroke    0
prevalentHyp       0
diabetes           0
totChol            0
sysBP              0
diaBP              0
BMI                0
heartRate          0
glucose            0
TenYearCHD         0
dtype: int64

In [11]:
df.corr()

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
male,1.000000,-0.029014,0.017188,0.197026,0.316023,-0.052203,-0.004550,0.005853,0.015693,-0.070064,-0.035879,0.058199,0.081705,-0.116913,0.005718,0.088374
age,-0.029014,1.000000,-0.164081,-0.213662,-0.192534,0.122036,0.057679,0.306799,0.101314,0.260691,0.394053,0.205586,0.135578,-0.012839,0.116951,0.225408
education,0.017188,-0.164081,1.000000,0.018297,0.008197,-0.010689,-0.035139,-0.080753,-0.038214,-0.022993,-0.128126,-0.061362,-0.135876,-0.053603,-0.033837,-0.053571
currentSmoker,0.197026,-0.213662,0.018297,1.000000,0.767055,-0.048621,-0.032980,-0.103710,-0.044285,-0.046211,-0.130281,-0.107933,-0.167483,0.062678,-0.054062,0.019448
cigsPerDay,0.316023,-0.192534,0.008197,0.767055,1.000000,-0.045847,-0.032711,-0.066444,-0.037086,-0.026182,-0.088523,-0.056473,-0.092888,0.075257,-0.056020,0.057646
BPMeds,-0.052203,0.122036,-0.010689,-0.048621,-0.045847,1.000000,0.115008,0.259125,0.051584,0.078973,0.252023,0.192387,0.099586,0.015172,0.048925,0.086805
prevalentStroke,-0.004550,0.057679,-0.035139,-0.032980,-0.032711,0.115008,1.000000,0.074791,0.006955,0.000105,0.057000,0.045153,0.024856,-0.017674,0.018065,0.061823
prevalentHyp,0.005853,0.306799,-0.080753,-0.103710,-0.066444,0.259125,0.074791,1.000000,0.077752,0.162683,0.696656,0.615840,0.300599,0.146777,0.082757,0.177458
diabetes,0.015693,0.101314,-0.038214,-0.044285,-0.037086,0.051584,0.006955,0.077752,1.000000,0.040161,0.111265,0.050260,0.086282,0.048986,0.605709,0.097344
totChol,-0.070064,0.260691,-0.022993,-0.046211,-0.026182,0.078973,0.000105,0.162683,0.040161,1.000000,0.207436,0.163423,0.115013,0.090678,0.044710,0.081807
sysBP,-0.035879,0.394053,-0.128126,-0.130281,-0.088523,0.252023,0.057000,0.696656,0.111265,0.207436,1.000000,0.783952,0.325172,0.182084,0.134561,0.216374
diaBP,0.058199,0.205586,-0.061362,-0.107933,-0.056473,0.192387,0.045153,0.615840,0.050260,0.163423,0.783952,1.000000,0.376317,0.181012,0.058499,0.145112
BMI,0.081705,0.135578,-0.135876,-0.167483,-0.092888,0.099586,0.024856,0.300599,0.086282,0.115013,0.325172,0.376317,1.000000,0.067318,0.082123,0.074788
heartRate,-0.116913,-0.012839,-0.053603,0.062678,0.075257,0.015172,-0.017674,0.146777,0.048986,0.090678,0.182084,0.181012,0.067318,1.000000,0.089386,0.022892
glucose,0.005718,0.116951,-0.033837,-0.054062,-0.056020,0.048925,0.018065,0.082757,0.605709,0.044710,0.134561,0.058499,0.082123,0.089386,1.000000,0.120451
TenYearCHD,0.088374,0.225408,-0.053571,0.019448,0.057646,0.086805,0.061823,0.177458,0.097344,0.081807,0.216374,0.145112,0.074788,0.022892,0.120451,1.000000

In [12]:
x =df[['age','prevalentHyp','sysBP','glucose','diabetes','diaBP']]
y= df['TenYearCHD']

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=123456)

In [20]:
def create_logistic_Reg_model():
    from sklearn.linear_model import LogisticRegressionCV
    model = LogisticRegressionCV()
    model.fit(x_train,y_train)
    return model

In [21]:
def create_KNN_model():
    from sklearn.neighbors import KNeighborsClassifier
    model = KNeighborsClassifier()
    model.fit(x_train,y_train)
    return model

In [22]:
def create_SVM_model():
    from sklearn.svm import SVC
    model = SVC()
    model.fit(x_train,y_train)
    return model

In [23]:
def create_naive_bayes_model():
    from sklearn.naive_bayes import GaussianNB
    model = GaussianNB()
    model.fit(x_train,y_train)
    return model

In [26]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score
def evaluate_model(model):
    y_pred = model.predict(x_test)
    accuracy = accuracy_score(y_test,y_pred)
    precision = precision_score(y_test,y_pred)
    recall = recall_score(y_test,y_pred)
    f1 = f1_score(y_test,y_pred)
    return f'{accuracy:.2f}', f'{precision:.2f}', f'{recall:.2f}', f'{f1:.2f}'

In [27]:
# list to keep all models
models =[]
#create all the models
models.append({"name" : "Logistic Regression",'model':create_logistic_Reg_model() })
models.append({"name" : "naive bayes",'model':create_naive_bayes_model() })
models.append({"name" : "KNN",'model':create_KNN_model()})
models.append({"name" : "SVM",'model':create_SVM_model()})

In [33]:
for model in models:
    accuracy,precision,recall,f1=evaluate_model(model['model'])
    model['accuracy'] = accuracy
    model['precision'] = precision
    model['recall'] = recall
    model['f1'] = f1

df_evaluation_report_test = pd.DataFrame(models,columns=['name','accuracy','precision','recall','f1']) 
df_evaluation_report_test

                  name accuracy precision recall    f1
0  Logistic Regression     0.85      0.38   0.02  0.05
1          naive bayes     0.82      0.29   0.18  0.22
2                  KNN     0.83      0.32   0.11  0.17
3                  SVM     0.85      0.43   0.02  0.05

In [34]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score
def evaluate_model(model):
    y_pred = model.predict(x_train)
    accuracy = accuracy_score(y_train,y_pred)
    precision = precision_score(y_train,y_pred)
    recall = recall_score(y_train,y_pred)
    f1 = f1_score(y_train,y_pred)
    return f'{accuracy:.2f}', f'{precision:.2f}', f'{recall:.2f}', f'{f1:.2f}'

In [35]:
# list to keep all models
models =[]
#create all the models
models.append({"name" : "Logistic Regression",'model':create_logistic_Reg_model() })
models.append({"name" : "naive bayes",'model':create_naive_bayes_model() })
models.append({"name" : "KNN",'model':create_KNN_model()})
models.append({"name" : "SVM",'model':create_SVM_model()})

In [37]:
for model in models:
    accuracy,precision,recall,f1=evaluate_model(model['model'])
    model['accuracy'] = accuracy
    model['precision'] = precision
    model['recall'] = recall
    model['f1'] = f1

df_evaluation_report_train = pd.DataFrame(models,columns=['name','accuracy','precision','recall','f1']) 
df_evaluation_report_train

                  name accuracy precision recall    f1
0  Logistic Regression     0.85      0.76   0.04  0.08
1          naive bayes     0.82      0.37   0.21  0.27
2                  KNN     0.86      0.61   0.19  0.30
3                  SVM     0.85      0.75   0.02  0.04